config/routes.rb
Rails.application.routes.draw do
  #scope ":locale", locale: /#{I18n.available_locales.join("|")}/ do
 # localized do
    get 'auth/login' => 'authentication#login', as: :login
    get 'auth/sign' => 'authentication#sign', as: :auth_sign
    delete 'auth/logout' => 'authentication#logout', as: :logout

    root to: 'pages#home', constraints: lambda { |request| request.session['account_id'].present? }
    root to: 'authentication#login'

    get '/all' => 'pages#home', as: :all
    get '/welcome' => 'pages#welcome', as: :welcome

    resources :accounts, path: 'u', only: [:show, :edit, :update] do
      member do
        post :transfer
        post :attach_transaction
      end
      collection do
        get :settings
        post :update_settings
      end
    end

    resources :follows do
      member do
        post :attach_transaction
      end
    end

    resources :favorites do
      member do
        post :attach_transaction
      end
    end

    resources :messages do
      member do
        post :repost
        post :reply
        post :attach_transaction
        post :tip
      end
    end

    post '/upload_avatar' => 'pages#upload_avatar', as: :upload_avatar

    resources :blocks, only: [:index, :show]
    resources :transactions, only: [:index, :show]

    get 'batches/show'
    post 'batches/:id/upload' => 'batches#upload'
    post 'batches/:id/attach_transaction' => 'batches#attach_transaction'
    post 'batches/:id/cancel' => 'batches#cancel'

  # ActivityPub routes
    get '/activity_pub/:account_id/outbox' => 'activity_pub#outbox', as: :ap_outbox
    get '/activity_pub/:account_id/account' => 'activity_pub#account', as: :ap_account
    get '/activity_pub/:account_id/inbox' => 'activity_pub#inbox', as: :ap_inbox
    get '/activity_pub/:account_id/followers' => 'activity_pub#followers', as: :ap_followers
    get '/activity_pub/:account_id/following' => 'activity_pub#following', as: :ap_following
    post '/activity_pub/:account_id/inbox' => 'activity_pub#inbox_incoming_message'
    get '/activity_pub/:message_id/message' => 'activity_pub#message', as: :ap_message
    get '/activity_pub/:version_id/activity' => 'activity_pub#activity', as: :ap_activity
    get '/.well-known/webfinger' => 'activity_pub#webfinger', as: :webfinger

    namespace :federated do
      resources :accounts, only: [:show] do
        collection do
          get :search
        end
      end
      resources :follows, only: [:create, :destroy]
      resources :messages, only: [:index]
    end
  #end
  #match "*.path", to: redirect("/#{I18n.default_locale}/%{path}"), :via => [:get, :post]
  #match "", to: redirect("/#{I18n.default_locale}"),:via => [:get,:post]
  mount Sidekiq::Web => '/sidekiq'
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.haml
.row.mt-3
  .col-3
  .col-6
    .card
      %h4.card-header Update your avatar
      .card-body
        -# = form_for(resource, as: resource_name, url: registration_path(resource_name), html: { method: :put, id: 'user-avatar' }) do |f|
        = form_tag upload_avatar_path, { method: :post, multipart: true } do
          .custom-file
            = file_field_tag(:avatar, class: 'custom-file-field')
            = label_tag(:avatar, 'Choose File', class: 'custom-file-label')
          
          %p.mt-2
            = submit_tag 'Upload', class: 'btn btn-primary'

.row.mt-3
  .col-3
  .col-6
    .card
      %h4.card-header Update your profile
      .card-body
        = form_for @user.managed_account do |f|
          .form-group
            = f.label :username
            = f.text_field :username, class: 'form-control'
          .form-group
            = f.label :display_name
            = f.text_field :display_name, class: 'form-control'
          .form-group
            = f.label :bio
            = f.text_area :bio, class: 'form-control', placeholder: 'Tell me your story'
          .form-group
            = f.label :location
            = f.text_field :location, class: 'form-control', placeholder: 'i.e. "Mars"'
          
          %p.mt-3
            = f.submit 'Update', class: 'btn btn-primary'

app/views/users/show.html.haml
- content_for(:title, "@#{@user.username}")
= javascript_pack_tag "user_page"
= stylesheet_pack_tag "user_page"
#js-user{ data: render(partial: 'user_page.json.jbuilder', locals: { messages: @messages, user: @user }) }

-# .row
-#   .col-3
-#     -# = gravatar_image_tag(@user.email, size: 256, class: 'img-responsive', gravatar: { secure: true, size: 256 })
-#     = image_tag(@user.avatar(:large), class: 'img-fluid')
-#     %h1= @user.username
-#     %p
-#       %strong Address:
-#       %small
-#         %code= '0x'+@account.address
    
-#     %p
-#       %strong Balance:
-#       %small= humanized_money_with_symbol @account.balance
    
-#     - if @user.bio.present?
-#       %p
-#         %strong Bio:
-#         %small= @user.bio
    
-#     - if @user.location.present?
-#       %p
-#         %strong Location:
-#         %small= @user.location
-#   .col-9
-#     %ul.nav.nav-tabs
-#       %li.nav-item
-#         %a.nav-link.active{href: '#posts', data: { toggle: :tab }, role: :tab }
-#           Posts
-#       %li.nav-item
-#         %a.nav-link{href: '#transactions', data: { toggle: :tab }, role: :tab }
-#           Transactions
    
-#     .tab-content.mt-3
-#       #posts.tab-pane.show.active{role: :tabpanel}
-#         %h3.mt-3 Recent posts:
-#         = render 'messages/index', messages: @user.messages.order('created_at desc')
-#       #transactions.tab-pane{role: :tabpanel}
-#         = render 'transactions/index', transactions: @transactions
    
    