config/routes.rb
Rails.application.routes.draw do
  #scope ":locale", locale: /#{I18n.available_locales.join("|")}/ do
 # localized do
    get 'auth/login' => 'authentication#login', as: :login
    get 'auth/sign' => 'authentication#sign', as: :auth_sign
    delete 'auth/logout' => 'authentication#logout', as: :logout

    root to: 'pages#home', constraints: lambda { |request| request.session['account_id'].present? }
    root to: 'authentication#login'

    get '/all' => 'pages#home', as: :all
    get '/welcome' => 'pages#welcome', as: :welcome

    resources :accounts, path: 'u', only: [:show, :edit, :update] do
      member do
        post :transfer
        post :attach_transaction
      end
      collection do
        get :settings
        post :update_settings
      end
    end

    resources :follows do
      member do
        post :attach_transaction
      end
    end

    resources :favorites do
      member do
        post :attach_transaction
      end
    end

    resources :messages do
      member do
        post :repost
        post :reply
        post :attach_transaction
        post :tip
      end
    end

    post '/upload_avatar' => 'pages#upload_avatar', as: :upload_avatar

    resources :blocks, only: [:index, :show]
    resources :transactions, only: [:index, :show]

    get 'batches/show'
    post 'batches/:id/upload' => 'batches#upload'
    post 'batches/:id/attach_transaction' => 'batches#attach_transaction'
    post 'batches/:id/cancel' => 'batches#cancel'

  # ActivityPub routes
    get '/activity_pub/:account_id/outbox' => 'activity_pub#outbox', as: :ap_outbox
    get '/activity_pub/:account_id/account' => 'activity_pub#account', as: :ap_account
    get '/activity_pub/:account_id/inbox' => 'activity_pub#inbox', as: :ap_inbox
    get '/activity_pub/:account_id/followers' => 'activity_pub#followers', as: :ap_followers
    get '/activity_pub/:account_id/following' => 'activity_pub#following', as: :ap_following
    post '/activity_pub/:account_id/inbox' => 'activity_pub#inbox_incoming_message'
    get '/activity_pub/:message_id/message' => 'activity_pub#message', as: :ap_message
    get '/activity_pub/:version_id/activity' => 'activity_pub#activity', as: :ap_activity
    get '/.well-known/webfinger' => 'activity_pub#webfinger', as: :webfinger

    namespace :federated do
      resources :accounts, only: [:show] do
        collection do
          get :search
        end
      end
      resources :follows, only: [:create, :destroy]
      resources :messages, only: [:index]
    end
  #end
  #match "*.path", to: redirect("/#{I18n.default_locale}/%{path}"), :via => [:get, :post]
  #match "", to: redirect("/#{I18n.default_locale}"),:via => [:get,:post]
  mount Sidekiq::Web => '/sidekiq'
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  def index
    @transactions = Transaction.by_block_number.page(params[:page])
  end

  def show
    @transaction = Transaction.find(params[:id])
  end
end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/views/transactions/_index.html.haml
%table.table.table-hover
  %thead.thead-light
    %tr.row
      %th.col-2 Hash
      %th.col Block
      %th.col Message
      %th.col-3 To
      %th.col-3 From
      -# %th.col.text-right Gas
      -# %th.col.text-right Gas Price
      %th.col-2.text-right Value
  %tbody
    - transactions.each do |transaction|
      %tr.row
        %td.col-2.text-truncate
          %small= link_to short_address(transaction.hash_address, length: 15), transaction
        %td.col
          %small= link_to transaction.block.number, transaction.block
        %td.col
          - if transaction.message
            %small= link_to transaction.message.id, transaction.message
        %td.col-3.text-truncate
          %small= link_to_account transaction.to_account
        %td.col-3.text-truncate
          %small= link_to_account transaction.from_account
        -# %td.col.text-right
        -#   %small= transaction.gas
        -# %td.col.text-truncate.text-right{title: transaction.gas_price}
        -#   %small= transaction.gas_price
        %td.col-2.text-truncate.text-right{title: transaction.value}
          %small= humanized_money_with_symbol transaction.value

app/views/transactions/index.html.haml
.row
  .col-12
    = render 'transactions/index', transactions: @transactions
    = paginate @transactions

app/views/transactions/show.html.haml
.row
  .col-12
    %h3.pre-wrap.mb-3.mt-0{title: @transaction.hash_address}
      = @transaction.hash_address
    
    %h5.mb-3
      Transaction created
      = time_ago_in_words @transaction.block.try(:timestamp) || @transaction.created_at
      ago

    .mt-3.mb-3

    - if @transaction.block_number.blank?
      .alert.alert-danger
        %h5
          This transaction is still pending.
          
    %dl.row
      - if confirmations = @transaction.confirmations
        %dt.col-3 Confirmations
        %dd.col-9= number_with_delimiter confirmations

      - if ENV['CHAIN_ID'] == '1'
        %dt.col-3 View on Etherscan
        %dd.col-9.text-truncate= link_to @transaction.hash_address, "https://etherscan.io/tx/#{@transaction.hash_address}", target: :_blank
      
      - if ENV['CHAIN_ID'] == '3'
        %dt.col-3 View on Etherscan
        %dd.col-9.text-truncate= link_to @transaction.hash_address, "https://ropsten.etherscan.io/tx/#{@transaction.hash_address}", target: :_blank

      - if @transaction.message
        %dt.col-3 Message
        %dd.col-9.text-truncate= link_to "View Message", @transaction.message
      
      - if @transaction.message.try(:user)
        %dt.col-3 User
        %dd.col-9= link_to "@#{@transaction.message.user.username}", user_path(@transaction.message.user.username)

      %dt.col-3 Value
      %dd.col-9= humanized_money_with_symbol @transaction.value
    
      %dt.col-3 Gas
      %dd.col-9= @transaction.gas

      %dt.col-3 Gas Price
      %dd.col-9= @transaction.gas_price

      %dt.col-3 From
      %dd.col-9
        = link_to_account(@transaction.from_account) if @transaction.from_account

      %dt.col-3 To
      %dd.col-9
        = link_to_account(@transaction.to_account) if @transaction.to_account

      %dt.col-3 Nonce
      %dd.col-9
        %code= @transaction.nonce

      %dt.col-3 Input
      %dd.col-9
        %code= @transaction.input

    %hr.mt-3.mb-3
    
    %h4 Block Details:

    %dl.row
      
      %dt.col-3 Block Number
      %dd.col-9= @transaction.block_number

      %dt.col-3 Block Hash
      %dd.col-9
        %code= @transaction.block_hash || "n/a"

    - if @transaction.transactable&.is_a?(Batch)
      - batch = @transaction.transactable
      %hr.mt-3.mb-3
      
      %h4 Batch Details:

      %dl.row
        - batch.batch_items.each do |batch_item|
          - batchable = batch_item.batchable
          %dt.col-3= batchable.class
          %dd.col-9
            - if batchable.is_a?(Message)
              = link_to batchable.title || batchable.body, message_path(batchable), class: 'text-truncate'
            - elsif batchable.is_a?(Account)
              'Account Update'
            - elsif batchable.is_a?(Favorite)
              = link_to "Favorite of post by @#{batchable.message.account.username}", message_path(batchable.message)
            - elsif batchable.is_a?(Follow)
              = link_to "Follow of @#{batchable.to_account.username}", account_path(batchable.to_account.username)
            - else
              = batchable.id